book: 
  chapters:
    - index.qmd
    - part: "Examples"
      chapters: 
        - chapters/00-intro-python-datascience.qmd
        - chapters/01-pandas-data-wrangling.qmd
        - chapters/01-data-and-models.qmd
        - chapters/02-black-box-classification.qmd
        - chapters/20-introduction-prediction.qmd
        - chapters/21-feature-engineering-and-overfitting.qmd
        - chapters/22-dissecting-bias.qmd
        - chapters/25-classification.qmd