book: 
  chapters:
    - index.qmd
    - part: "Data Wrangling and Exploration"
      chapters: 
        - chapters/00-intro-python-datascience.qmd
        - chapters/01-pandas-data-wrangling.qmd
        - chapters/02-visualization.qmd
        - chapters/03-data-wrangling.qmd
    - part: "Machine Learning and Prediction"
      chapters:
        - chapters/20-introduction-prediction.qmd
        - chapters/21-feature-engineering-and-overfitting.qmd
        - chapters/22-dissecting-bias.qmd
        - chapters/25-classification.qmd
        - chapters/26-compas.qmd
        - chapters/27-neural-prediction.qmd