project:
  type: book
  output-dir: docs

book: 
  title: "Applied Data Science"
  author: "Michael Linderman and Phil Chodrow"
  date: "01/05/2026"
  body-footer: |
        <br> <br> <span style="color:grey;">&#169; Michael Linderman and Phil Chodrow, 2025-2026</span>
  sidebar: 
    search: false
  chapters:
    - index.qmd
    - part: "Data Wrangling and Exploration"
      chapters: 
        - source/10-intro-python-datascience.qmd
        - source/11-pandas-data-wrangling.qmd
        - source/12-visualization.qmd
        - source/13-data-wrangling.qmd
    - part: "Machine Learning and Prediction"
      chapters:
        - source/20-introduction-prediction.qmd
        - source/21-feature-engineering-and-overfitting.qmd
        - source/22-dissecting-bias.qmd
        - source/25-classification.qmd
        - source/26-compas.qmd
        - source/27-neural-prediction.qmd
    - part: "Generative Models and Applications"
      chapters:
        - source/30-prediction-generation.qmd

bibliography: refs.bib

format:
  html:
    theme: [cosmo, custom.scss]
    css: styles.css
    toc: true
    number-depth: 0
    reference-location: margin
    callout-icon: false;
    callout-appearance: simple
    fig-cap-location: margin
    highlight-style: atom-one

    

jupyter: python3

execute: 
  cache: false

profile:
  group: 
    - [preview, publish]

mermaid: 
  theme: neutral

# Enable local paths for images and data in default context (but full URL for live notebooks)
site-url: "."