book: 
  chapters:
    - index.qmd
    - part: "Data Wrangling and Exploration"
      chapters: 
        - source/00-intro-python-datascience.qmd
        - source/01-pandas-data-wrangling.qmd
        - source/02-visualization.qmd
        - source/03-data-wrangling.qmd
    - part: "Machine Learning and Prediction"
      chapters:
        - source/20-introduction-prediction.qmd
        - source/21-feature-engineering-and-overfitting.qmd
        - source/22-dissecting-bias.qmd
        - source/25-classification.qmd
        - source/26-compas.qmd
        - source/27-neural-prediction.qmd
        - source/29-compas.qmd
    - part: "Generative Models and Applications"
      chapters:
        - source/30-prediction-generation.qmd
